// ─── Cross-Reference Linking Module ─────────────────────────────────
// Universal cross-reference system for entity linking across the app.
// Modular architecture: models, commands, resolver, registry.

pub mod models;
pub mod commands;
pub mod resolver;
pub mod registry;

// Re-export public types for convenience
pub use models::{
    CrossReference,
    EntityReference,
    CachedEntity,
    ResolveReferenceRequest,
    BatchValidateRequest,
    CrossReferenceError,
};

// Re-export commands - Tauri needs these at module root to find __cmd__* functions
pub use commands::{
    resolve_entity_reference,
    batch_validate_references,
    get_all_entities_for_cache,
    get_entity_backlinks,
    update_reference_registry,
    get_activities_for_date_autocomplete,
    get_recent_grid_dates,
    search_grid_months,
    search_grid_dates_in_month,
};

// Re-export __cmd__ functions generated by #[tauri::command] macro
pub use commands::{
    __cmd__resolve_entity_reference,
    __cmd__batch_validate_references,
    __cmd__get_all_entities_for_cache,
    __cmd__get_entity_backlinks,
    __cmd__update_reference_registry,
    __cmd__get_activities_for_date_autocomplete,
    __cmd__get_recent_grid_dates,
    __cmd__search_grid_months,
    __cmd__search_grid_dates_in_month,
};
